name: example
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  sqflite_sqlcipher: ^2.1.0
  localchain:
    path: ../

dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

